# name: CI

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   build-and-test:
#     strategy:
#       matrix:
#         node-version: [20.x, 22.x]
#       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     name: Build with ${{ matrix.node-version }}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: pnpm/action-setup@v3
#         with:
#           version: 8
#       - uses: actions/setup-node@v4
#         with:
#           node-version: latest
#       - run: pnpm install
#       - run: pnpm run build
#       - run: pnpm run test
#       - run: pnpm run test:e2e
